import { NextResponse } from 'next/server';
import { store } from '@/lib/store';
import { invalidateBoard } from '@/lib/data/board-cache';
import { DEMO_VOLUNTEERS, buildVolunteer } from '@/lib/data/volunteers';
import fixture from '@/lib/data/fixtures/seeded-board.json';

export const dynamic = 'force-dynamic';

/**
 * Loads a pre-generated board, for hosts that cannot run the real seeder.
 *
 * The full seeder at /api/dev/seed-needs runs every demo report through Gemma
 * live, which takes about three and a half minutes. That is the right thing to
 * do locally, and impossible on a serverless host where a function is capped at
 * sixty seconds.
 *
 * So this loads the output of a previous real run, committed at
 * lib/data/fixtures/seeded-board.json. To be clear about what that means: the
 * routing, urgency, translations and crew assignments in that file were all
 * produced by gemma4:e4b-it-qat, and each record still carries the ai_model
 * field naming it. Nothing was written by hand. But they were produced ahead of
 * time rather than in front of you.
 *
 * Records loaded this way are marked `seed_mode: 'prebuilt'` so the difference
 * is visible in the data rather than only in this comment. Anything filed after
 * loading, including through the spawn control, is triaged live as usual.
 *
 *   POST /api/dev/quick-seed
 */
export async function POST() {
  try {
    await store().removeWhere(
      'needs',
      (d: any) => typeof d.source_type === 'string' && d.source_type.startsWith('seed:')
    );

    const now = Date.now();
    const rows = fixture as Array<Record<string, unknown>>;

    // Spread the ages across the last two days so the board reads as a live
    // backlog rather than a batch created in one second.
    for (let i = 0; i < rows.length; i++) {
      const ageMinutes = 5 + Math.round((i / Math.max(rows.length - 1, 1)) * 2800);
      const at = new Date(now - ageMinutes * 60000).toISOString();
      await store().add('needs', {
        ...rows[i],
        created_at: at,
        updated_at: at,
        seed_mode: 'prebuilt',
      });
    }

    // Volunteers are static records, so there is nothing to pre-generate.
    await store().removeWhere('volunteers', (v: any) => v.city === 'Rajkot');
    for (const v of DEMO_VOLUNTEERS) {
      await store().add('volunteers', buildVolunteer(v));
    }

    invalidateBoard();

    return NextResponse.json({
      ok: true,
      needs: rows.length,
      volunteers: DEMO_VOLUNTEERS.length,
      note: 'Pre-generated by Gemma in an earlier run. Use /api/dev/seed-needs to regenerate live.',
    });
  } catch (error) {
    return NextResponse.json(
      { ok: false, error: error instanceof Error ? error.message : String(error) },
      { status: 500 }
    );
  }
}
